// Copiato da modes/src/core/testi.ts con scripts/sync-content.mjs, non modificare qui.
// Testi delle modalità in italiano e inglese.
import { impostazioni } from "./impostazioni";

const T = {
  jukeJoint: { it: "Il Juke Joint", en: "The Juke Joint" },
  sottotitolo: { it: "Stasera si suona per divertirsi", en: "Tonight we play for fun" },
  tuaArmonica: { it: "Armonica", en: "Harp" },
  lingua: { it: "IT", en: "EN" },
  micAccendi: { it: "Accendi il microfono", en: "Turn on the mic" },
  micAcceso: { it: "Microfono acceso", en: "Mic on" },
  micNegato: { it: "Microfono non disponibile: usa la tastiera", en: "Mic unavailable: use the keyboard" },
  tastiera: { it: "Tastiera: 1-0 soffio · Q-P aspirato · Spazio = bend", en: "Keyboard: 1-0 blow · Q-P draw · Space = bend" },
  cuffie: { it: "Con le cuffie il microfono sente solo te", en: "With headphones the mic hears only you" },
  gioca: { it: "Suona", en: "Play" },
  indietro: { it: "Indietro", en: "Back" },
  esci: { it: "Esci", en: "Quit" },
  riprova: { it: "Ancora!", en: "Again!" },
  continua: { it: "Continua", en: "Continue" },
  record: { it: "Record", en: "Best" },
  nuovoRecord: { it: "Nuovo record!", en: "New best!" },
  pronti: { it: "Pronti…", en: "Ready…" },
  senti: { it: "Senti", en: "Hearing" },

  // Jam
  jamTitolo: { it: "Jam Libera", en: "Free Jam" },
  jamPoster: { it: "Improvvisa sul blues. Il pubblico ti ascolta.", en: "Improvise over the blues. The crowd is listening." },
  jamModoLibero: { it: "Assolo", en: "Solo" },
  jamModoScambio: { it: "Botta e risposta", en: "Trading" },
  jamModoLiberoDesc: { it: "La band ti accompagna, il palco è tuo", en: "The band backs you, the stage is yours" },
  jamModoScambioDesc: { it: "Zia Mae suona due battute, tu rispondi", en: "Aunt Mae plays two bars, you answer" },
  jamGiri: { it: "Giri", en: "Choruses" },
  tempo: { it: "Tempo", en: "Tempo" },
  lento: { it: "Lento", en: "Slow" },
  medio: { it: "Medio", en: "Medium" },
  veloce: { it: "Veloce", en: "Fast" },
  registra: { it: "Registra il tuo assolo", en: "Record your solo" },
  hype: { it: "Pubblico", en: "Crowd" },
  hype0: { it: "Tiepido", en: "Lukewarm" },
  hype1: { it: "Si scalda", en: "Warming up" },
  hype2: { it: "Caldo", en: "Hot" },
  hype3: { it: "In fiamme", en: "On fire" },
  hype4: { it: "LEGGENDA", en: "LEGEND" },
  consigliate: { it: "Note d'accordo", en: "Chord tones" },
  tuoTurno: { it: "Tocca a te!", en: "Your turn!" },
  ascoltaMae: { it: "Ascolta Zia Mae", en: "Listen to Aunt Mae" },
  fineJam: { it: "Fine del set", en: "End of the set" },
  riascolta: { it: "Riascolta", en: "Play back" },
  ferma: { it: "Ferma", en: "Stop" },
  scarica: { it: "Scarica", en: "Download" },
  frasi: { it: "Frasi", en: "Phrases" },
  bendFatti: { it: "Bend", en: "Bends" },
  cambiPresi: { it: "Cambi presi", en: "Changes hit" },
  lickTrovati: { it: "Lick scoperti", en: "Licks found" },
  hypeMax: { it: "Pubblico al massimo", en: "Peak crowd" },
  punti: { it: "Punti", en: "Score" },
  ilTuoAssolo: { it: "Il tuo assolo", en: "Your solo" },
  silenzioLungo: { it: "Il pubblico aspetta: suona!", en: "The crowd is waiting: play!" },
  troppeNote: { it: "Respira: lascia spazio tra le frasi", en: "Breathe: leave space between phrases" },

  // Riff
  riffTitolo: { it: "La Strada dei Riff", en: "Riff Highway" },
  riffPoster: { it: "I riff ti vengono incontro: prendili a tempo.", en: "Riffs roll towards you: catch them on the beat." },
  concerto: { it: "Concerto", en: "Gig" },
  pratica: { it: "Prova", en: "Practice" },
  concertoDesc: { it: "Con la band, a tempo. Non si ferma.", en: "With the band, in time. It won't stop." },
  praticaDesc: { it: "Senza fretta: il riff aspetta la tua nota.", en: "No rush: the riff waits for your note." },
  perfetto: { it: "PERFETTO", en: "PERFECT" },
  bene: { it: "BENE", en: "GOOD" },
  mancata: { it: "MANCATA", en: "MISS" },
  combo: { it: "combo", en: "combo" },
  fuoco: { it: "IN FIAMME ×", en: "ON FIRE ×" },
  precisione: { it: "Precisione", en: "Accuracy" },
  comboMax: { it: "Combo massima", en: "Best combo" },
  livello: { it: "Livello", en: "Level" },
  daSbloccare: { it: "Prendi 1 stella nel riff prima", en: "Get 1 star on the previous riff" },
  scegliRiff: { it: "Scegli un disco", en: "Pick a record" },
  attesaNota: { it: "Suona", en: "Play" },

  // Volo
  voloTitolo: { it: "Il Volo della Lucciola", en: "Firefly Flight" },
  voloPoster: { it: "La tua nota la fa volare. Piega le note per salire e scendere.", en: "Your note makes it fly. Bend notes to dip and climb." },
  voloAiuto: { it: "Più la nota è acuta, più la lucciola sale. Raccogli le luci!", en: "The higher the note, the higher the firefly. Collect the lights!" },
  luci: { it: "Luci", en: "Lights" },
  scegliVolo: { it: "Scegli il volo", en: "Choose a flight" },
  silenzio: { it: "silenzio", en: "silence" },
} satisfies { [k: string]: { it: string; en: string } };

export type IdTesto = keyof typeof T;
export const t = (id: IdTesto): string => T[id][impostazioni.lingua];
/** Per i testi bilingui presi dai contenuti (es. percorso.json). */
export const tl = (x: { it: string; en: string }): string => x[impostazioni.lingua];

const EXTRA = {
  cuffieSi: { it: "Cuffie", en: "Headphones" },
  cuffieNo: { it: "Casse", en: "Speakers" },
  cuffieDesc: { it: "Con le cuffie suona tutta la band. Con le casse restano i tamburi, così il microfono sente solo te.", en: "With headphones the whole band plays. With speakers only the drums stay, so the mic hears just you." },
  registraSi: { it: "Registra: sì", en: "Record: on" },
  registraNo: { it: "Registra: no", en: "Record: off" },
  collezione: { it: "Collezione di lick", en: "Lick collection" },
  collezioneAiuto: { it: "Suonali durante la jam per scoprirli", en: "Play them during a jam to discover them" },
  entra: { it: "Entra", en: "Joining" },
  strumento_basso: { it: "il contrabbasso", en: "the upright bass" },
  strumento_piano: { it: "il piano", en: "the piano" },
  strumento_batteria: { it: "la batteria", en: "the drums" },
  strumento_elettrica: { it: "la chitarra elettrica", en: "the electric guitar" },
  ev_cambio: { it: "CAMBIO!", en: "CHANGE!" },
  ev_bend: { it: "BEND!", en: "BEND!" },
  ev_blue: { it: "blue note", en: "blue note" },
  ev_lunga: { it: "NOTA LUNGA", en: "LONG NOTE" },
  ev_fiato: { it: "CHE FIATO!", en: "WHAT A BREATH!" },
  ev_frase: { it: "frase", en: "phrase" },
  ev_risolta: { it: "RISOLTA", en: "RESOLVED" },
  ev_eco: { it: "ECO!", en: "ECHO!" },
  ev_tasca: { it: "A TEMPO!", en: "IN THE POCKET!" },
  ev_lick: { it: "LICK!", en: "LICK!" },
  ev_lickNuovo: { it: "LICK SCOPERTO", en: "LICK DISCOVERED" },
  ev_risposta: { it: "BELLA RISPOSTA", en: "NICE ANSWER" },
  ev_copia: { it: "COPIATA!", en: "NAILED IT!" },
  ev_estensione: { it: "TUTTA L'ARMONICA", en: "FULL RANGE" },
  livelloSu: { it: "Il pubblico è", en: "The crowd is" },
  giro: { it: "Giro", en: "Chorus" },
  nuovi: { it: "nuovi", en: "new" },
  nessunaRegistrazione: { it: "Registrazione non disponibile in questo browser", en: "Recording not available in this browser" },
} satisfies { [k: string]: { it: string; en: string } };
export type IdExtra = keyof typeof EXTRA;
export const tx = (id: IdExtra): string => EXTRA[id][impostazioni.lingua];
